language: cpp

sudo: required
dist: bionic

branches:
  only:
    - master

env:
  global:
    - QT_VER=5.15.0

git:
  depth: 175


install: .travis/install.sh
script: .travis/script.sh
deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    local-dir: dist
    repo: mmatyas/pegasus-deploy-staging
    target-branch: continuous-$TARGET
    skip-cleanup: true

jobs:
  include:
  - env: TARGET=x11-static

  # Collect and deploy artifacts
  - stage: release
    install: skip
    script: .travis/release.sh
    deploy:
      - provider: bintray
        file: "$TRAVIS_BUILD_DIR/.travis/bintray_deb.json"
        user: "mmatyas"
        key:
          secure: grK+TcvmcnfEyFbBs7kTh6S/awFPQLzNROW5pwYcVc664NP4GxEFd+tl3CqkIuUv1n8HR/x/VWqIc7se12HQx41FnSYqJeArNPI7+gTHHyoR2AtcHptUR1BJUfemlrRhkjbd6dwfdwaeRDt3B1aIy9D0EG8gDgmt6tMIK390AFptwhbvarVZq2nlAnMJ3/DMWIzDXn2Kx6xErQji5LFCOmfFnOCw00z1uDpmTrO6QnfdwlORowVfhoT9SYdPtSQksYyi5Lzjeu0UmxIQtlGisqmiqPOdMb9ted0aNRhfHPYO2Dim+hOwBk+N9GO7AgHDjInkADOwtPxE7qcm5prLO0kV5Jc1ykWB4WWlBDQilggpwm2PbJbsf4zT6Dc7yRzAuarvlFkY8l8zvd4giyMzGCulMWHespglTF8YQDD6B6n78+ePeUqgq0beN/vQP5kAMIJbpXXnPrX9gHS3upO2F9HTQY1WLq+Aq0aub/9ZhEOkGMxzWdWl9u/CsoH2dySDyiyfOuhJuXyEGcfL4jL3yA8JPrZ18ApsEx3CJnnAvdJgy//0tkD5ajucEJVcsfQ5DW/HxfAT6APMMxkqvBiwxkipiUG52klXfwPfxw9oz6ZLC53HwF9MjxowOJnAf4MLbd3/H9AK7CPODPKt/n1ybVzEa3Awl9p2R/niNzaAYQA=
        skip_cleanup: true

  # Coverage testing
  - stage: test
    name: Coverage
    env: TARGET=x11-static RUN_COV=1
    script: .travis/script.sh
    deploy: null

services:
  - xvfb
